version: '2'

services:
  af-db:
    container_name: "af-db"
    image: mysql:5.7
    volumes:
      - ./db:/var/lib/mysql
      - ./mysql.cnf:/etc/mysql/conf.d/mysql.cnf
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: airflow-db
      MYSQL_DATABASE: airflow
      MYSQL_USER: airflow
      MYSQL_PASSWORD: ariflow-db
      MYSQL_PORT: 3306
      TZ: 'Asia/Tokyo'
    ports:
      - "3306:3306"
#      - "33060:33060"
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci

  af-redis:
    container_name: "af-redis"
    image: redis:4-alpine
    restart: always
    ports:
      - "6379:6379"
